- .github/actions/setup/action.yml
- .github/workflows/publish.yml
- scripts/release.ts
Porting hotfixes on `releases/0.3` branch:
https://github.com/autifyhq/autify-cli/pull/25
https://github.com/autifyhq/autify-cli/pull/27
> Port hotfixes from `releases/0.3`

- README.md
- package-lock.json
- package.json
- scripts/generate-api-commands.ts
- src/commands/mobile/api/describe-test-result.ts
- src/commands/mobile/api/list-test-results.ts
This commit adds new commands for `mobile api` by updating
`@autifyhq/autify-sdk` to `0.2.0`.
It also requires to adjust `generate-api-commands.ts`.
> Update mobile commands

- integration-test/__recordings__/mobile%20build%20upload%20--json%20--workspace-id%3DnYmF1n%20android.apk/polly-proxy_3343057686/recording.har
- integration-test/__recordings__/mobile%20test%20run%20--build-id%3D8DuzpG%20--wait%20https%3A%2F%2Fmobile-app.autify.com%2Fprojects%2FnYmF1n%2Ftest_plans%2FDEWt9g/polly-proxy_3343057686/recording.har
- integration-test/__recordings__/mobile%20test%20run%20--build-id%3D8DuzpG%20https%3A%2F%2Fmobile-app.autify.com%2Fprojects%2FnYmF1n%2Ftest_plans%2FDEWt9g/polly-proxy_3343057686/recording.har
- integration-test/__recordings__/mobile%20test%20run%20--build-path%3Dandroid.apk%20--wait%20https%3A%2F%2Fmobile-app.autify.com%2Fprojects%2FnYmF1n%2Ftest_plans%2FDEWt9g/polly-proxy_3343057686/recording.har
- integration-test/__recordings__/mobile%20test%20run%20--build-path%3Dandroid.apk%20https%3A%2F%2Fmobile-app.autify.com%2Fprojects%2FnYmF1n%2Ftest_plans%2FDEWt9g/polly-proxy_3343057686/recording.har
- integration-test/__recordings__/mobile%20test%20run%20--build-path%3Dios.app%20--wait%20https%3A%2F%2Fmobile-app.autify.com%2Fprojects%2FnYmF1n%2Ftest_plans%2FDPjteo/polly-proxy_3343057686/recording.har
- integration-test/__recordings__/mobile%20test%20run%20--build-path%3Dios.app%20https%3A%2F%2Fmobile-app.autify.com%2Fprojects%2FnYmF1n%2Ftest_plans%2FDPjteo/polly-proxy_3343057686/recording.har
- integration-test/__recordings__/web%20test%20run%20--wait%20https%3A%2F%2Fapp.autify.com%2Fprojects%2F743%2Fscenarios%2F91437/polly-proxy_3343057686/recording.har
- integration-test/__recordings__/web%20test%20run%20https%3A%2F%2Fapp.autify.com%2Fprojects%2F743%2Fscenarios%2F91437/polly-proxy_3343057686/recording.har
- integration-test/__snapshots__/golden/mobileBuildUploadJson.test.js.snap
- integration-test/__snapshots__/golden/mobileTestRun.test.js.snap
- integration-test/__snapshots__/golden/mobileTestRunAndroid.test.js.snap
- integration-test/__snapshots__/golden/mobileTestRunAndroidWait.test.js.snap
- integration-test/__snapshots__/golden/mobileTestRunIos.test.js.snap
- integration-test/__snapshots__/golden/mobileTestRunIosWait.test.js.snap
- integration-test/__snapshots__/golden/webTestRun.test.js.snap
- integration-test/__snapshots__/golden/webTestRunWait.test.js.snap
- integration-test/package.json
- integration-test/src/bin/autify-cli-integration-test.ts
- integration-test/src/test/golden/mobileBuildUploadJson.test.ts
- integration-test/src/test/golden/mobileTestRunAndroidWait.test.ts
- integration-test/src/test/golden/mobileTestRunIosWait.test.ts
- package.json
To provide more capabilities to `autify-with-proxy`,
this commit adds more records for additional mobile commands.
> Add more mobile integration tests

- .devcontainer/Dockerfile
- Avoid annoying message of permission denied
- Install `tig`
- Install `autify-cli`
> Misc fix for devcontainer

- README.md
- src/commands/connect/access-point/set.ts
- src/commands/connect/client/install.ts
- src/commands/connect/client/start.ts
- src/commands/web/test/run.ts
Since there is no integration test, we'd like to mark them as experimental for now.
> Mark connect related commands experimental

- src/autify/connect/installClient.ts
- src/autify/connect/spawnClient.ts
> Fix minor bugs on message of `connect client start`

- patches/@oclif+plugin-update+3.0.0.patch
- patches/oclif+3.2.1.patch
Previous commit is still not enough to fix the update functionality.
> Fix update bugs of `oclif` patches

- README.md
- integration-test/__recordings__/web%20test%20run%20--autify-connect-client%20--wait%20https%3A%2F%2Fapp.autify.com%2Fprojects%2F743%2Fscenarios%2F91437/polly-proxy_3343057686/recording.har
- integration-test/__snapshots__/golden/webTestRunAutifyConnectClient.test.js.snap
- integration-test/src/test/helpers/execAutifyCli.ts
- package-lock.json
- package.json
- src/autify/connect/client-manager/ClientManager.ts
- src/autify/connect/client-manager/DebugServerClient.ts
- src/autify/connect/client-manager/StateMachine.ts
- src/commands/connect/client/start.ts
- src/commands/web/test/run.ts
Most of the case, the customers don't care about the debug server port of Autify Connect Client.
This commit uses a random port if it's not specified via command line and it will reduce a chance of port conflict.
> Use random port for connect client debug server

- README.md
- src/autify/connect/client-manager/ClientManager.ts
- src/commands/connect/access-point/create.ts
- src/commands/connect/client/start.ts
- src/commands/web/test/run.ts
Just updating help messages and a method name.
> Small update on help and method name

- integration-test/src/test/helpers/execAutifyCli.ts
- src/autify/connect/client-manager/ClientManager.ts
The previous commit wasn't enough.
> Fix workaround for terminate error

- src/autify/connect/client-manager/ClientManager.ts
- src/autify/connect/client-manager/StateMachine.ts
Previous commit has a bug that the error isn't thrown when the client binary is not installed and the command is `web test run`.
This commit improves error handling of client manager.
> Fix error handling of connect client

- README.md
- package-lock.json
- package.json
- scripts/generate-api-commands.ts
- src/commands/web/api/create-access-point.ts
- src/commands/web/api/delete-access-point.ts
- src/commands/web/api/list-access-points.ts
Introducing:
- Updating `web api execute-schedule`
- Adding `web api list-access-points`
In addition, this commit also adds `web api create-access-point` and `web api delete-access-point` which were missed to generate in the previous update.
> Update autify-sdk-js to 0.6.0

- bin/dev
- bin/run
It is better to display response body in the error message if it's available.
> Update error message of AxiosError

- README.md
- src/commands/web/api/describe-result.ts
- src/commands/web/api/execute-schedule.ts
- src/commands/web/api/list-results.ts
We forgot to generate commands and update README in the previous PR.
This commit just does them.
> Generate commands and README

- renovate.json
To get minor update it seems we need to change `rangeStrategy`
https://github.com/renovatebot/renovate/discussions/13093
https://docs.renovatebot.com/configuration-options/#rangestrategy
> Change rangeStrategy to bump to create a PR to update minor version

- renovate.json
It seems it tried to create but skipped because of this limit
> Increase prConcurrentLimit to make sure it sends a PR for minor

- renovate.json
To avoid queueing a lot of jobs
> Reduce concurrent limit

- package-lock.json
- package.json
- src/commands/web/api/create-test-plan-variable.ts
- src/commands/web/api/delete-test-plan-variable.ts
- src/commands/web/api/describe-result.ts
- src/commands/web/api/list-test-plan-variable.ts
- src/commands/web/api/update-test-plan-variable.ts
> Generate client command for test plan variable and describe result

- .github/actions/setup/action.yml
- integration-test/package.json
- integration-test/src/bin/autify-cli-integration-test.ts
- integration-test/src/bin/autify-with-proxy.ts
- integration-test/src/test/helpers/execAutifyCli.ts
- integration-test/tsconfig.json
- package-lock.json
- package.json
- src/autify/connect/client-manager/DebugServerClient.ts
- src/autify/connect/installClient.ts
upgraded Node version to 22 and removed dependency to node-fetch
> [PLAT-440] chore: upgraded Node version to 22 and removed dependency to node-fetch

- .gitignore
- README.md
- integration-test/__recordings__/mobile%20build%20upload%20ios.ipa%20--workspace-id%3D4yyFEL/polly-proxy_3343057686/recording.har
- integration-test/__recordings__/mobile%20test%20run%20https%3A%2F%2Fmobile-app.autify.com%2Fprojects%2F4yyFEL%2Ftest_plans%2F1EtZ0P%20--build-path%3Dios.ipa%20--wait/polly-proxy_3343057686/recording.har
- integration-test/__snapshots__/golden/mobileBuildUploadIosIPA.test.js.snap
- integration-test/__snapshots__/golden/mobileTestRunIosIPAWait.test.js.snap
- integration-test/src/bin/autify-mobile-generate-fake-app.ts
- integration-test/src/commands.ts
- integration-test/src/test/golden/mobileBuildUploadIosIPA.test.ts
- integration-test/src/test/golden/mobileTestRunIosIPAWait.test.ts
- src/autify/mobile/inspectBuildFile.ts
- src/commands/mobile/build/upload.ts
- src/commands/mobile/test/run.ts
Support uploading .ipa file for Nocode Mobile
> Support .ipa file for mobile commands

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
Modify the devcontainer to work properly in the current environment.
> chore: update devcontainer configuration

- e2e-test/mobile/local-execution-flow.test.ts
I think 30 minutes is too long. Let's reduce it. Also, I added code to ensure the test to finished.
> Adjust e2e timeout

- .github/workflows/e2e-tests.yml
Discussion: https://autifyhq.slack.com/archives/C0414JQMLLT/p1744857708869229
> Use xlarge runner for e2e tests

- e2e-test/mobile/local-execution-flow.test.ts
- src/autify/mobile/mobilelink/installBinary.ts
- src/autify/mobile/mobilelink/mobile-link-manager/MobileLinkManager.ts
It includes
- Local Android device feature
- Windows support
> Update mobilelink to 0.4.5

- src/autify/mobile/mobilelink/installBinary.ts
> Bump mobilelink to 0.4.6
