autifyhq/autify-cli

.github/dependabot.yml

This commit changes interval of `npm` scan to weekly and adds
`github-actions` scan as well.

More dependabot checks

---

.github/actions/setup/action.yml
.github/workflows/integration-tests.yml
.github/workflows/publish.yml
.github/workflows/upload.yml
.gitignore
README.md
integration-test/package.json
package.json
scripts/release.ts

To trigger stable promotion by GitHub release, this commit introduces
a new workflow "Publish" that executes S3 promotion, Homebrew update and
npm publish.
Note: This commit is WIP to test the workflow for beta publish.
Need to comment out in `publishCommand()` of `scripts/release.ts`.

Add publish workflow

---

integration-test/package.json
package-lock.json
package.json
scripts/release.ts

We verified the publish workflow works with beta version.
Thus, we can remove the TODO to prepare 0.3.0 release.
Also, fixed minor dependencies including using @autifyhq/autify-sdk@0.1.0.

Fix TODO for publish and minor dependencies

---

.github/actions/setup/action.yml
.github/workflows/publish.yml

Since we switched the trigger for publish to `release`,
`github.ref_name` is the tag name, not its branch name.
Therefore, we need to adjust the `setup` action to deal it differently.
Note: Need to cherry-pick to `main` branch once confirmed it's working expectedly.

Fix aws-credentials for publish workflow

---

scripts/release.ts

Previously, the command was wrong especially when bumping from
`0.1.1-rc.0` to `0.1.1`. It bumped to `0.2.0` mistakenly:
```
$ npm version prerelease --preid rc --no-git-tag-version
v0.1.0-rc.0
$ npm version minor --no-git-tag-version
v0.1.0
$ npm version prepatch --preid rc --no-git-tag-version
v0.1.1-rc.0
$ npm version minor --no-git-tag-version
v0.2.0
```
By this change, it correctly bumps versions:
```
$ npm version prerelease --preid rc --no-git-tag-version
v0.1.0-rc.0
$ npm version patch --no-git-tag-version
v0.1.0
$ npm version prepatch --preid rc --no-git-tag-version
v0.1.1-rc.0
$ npm version patch --no-git-tag-version
v0.1.1
```
Note: This commit needs to be cherry-picked to `main`.

Fix bump command for stable

---

.github/workflows/integration-tests.yml
install-cicd.bash
scripts/release.ts

As we grow more integrations, some CI/CD solutions want to install
Autify CLI in current working directory. `install-cicd.bash` is a variant
of `install-standalone.sh` to install Autify CLI to CWD.

Add install-cicd.bash

---

install-cicd.bash

Sometimes the workspace is reused in CI/CD solutions and
the previously installed files should be delete before install.

Delete previously installed files in `install-cicd.bash`

---

README.md
package-lock.json
package.json
src/autify/mobile/createZip.ts
src/autify/mobile/getTestResultUrl.ts
src/autify/mobile/parseTestResultUrl.ts
src/autify/mobile/runTest.ts
src/autify/mobile/waitTestResult.ts
src/commands/mobile/test/run.ts
src/commands/mobile/test/wait.ts
test/commands/mobile/test/run.test.ts
test/commands/mobile/test/wait.test.ts

Just implementing `autify mobile test run/wait` by mostly copying from
`autify web test run/wait`. No integration test yet.
The biggest difference from `web` is uploading build file.
Only iOS app needs to be zipped so that we don't support Windows
and use `zip` command to make it easier.

Add `mobile test run/wait`

---

integration-test/package.json
package-lock.json
src/autify/getWaitIntervalSecond.ts
src/autify/mobile/waitTestResult.ts
src/autify/web/waitTestResult.ts
src/commands/mobile/test/wait.ts
src/commands/web/test/wait.ts
src/config.ts

For integration tests, we don't have to wait 1 second interval
while waiting the test result.
`AUTIFY_TEST_WAIT_INTERVAL_SECOND` config can override the interval
and speed up the integration test executions.

Add `AUTIFY_TEST_WAIT_INTERVAL_SECOND`

---

src/autify/web/runTest.ts
src/commands/web/test/run.ts

Since `executeScenario` API supports overriding Autify Connect Key,
we'd like to support it via `autify web test run` as well.
Until test plan execution supports the same overriding,
this option is only valid for test scenario executions.

Add `--autify-connect-key` to `web test run`

---

integration-test/package.json
integration-test/src/test/helpers/generateFakeApp.ts
integration-test/src/test/helpers/testAutifyCliSnapshot.ts

Since the current code has a tiny race condition when creating fake apps
because `jest` runs multiple test files in parallel.
This commit introduces a new npm task to generate fake apps and
run it before running `jest` so that we can ensure that this process
runs only once.

Run `generate-fake-app` before running `jest`

---

README.md
src/autify/web/runTest.ts
src/commands/web/test/run.ts

Since we're going to rename some terminologies,
`--autify-connect` is more suitable than `--autify-connect-key`.
We're going to just rename it and break backward compatibility
but it's fine since we've just released the previous version
and Autify Connect is an optional feature as of today.

Rename to `--autify-connect`

---

README.md
package-lock.json
package.json
src/autify/connect/installClient.ts
src/autify/connect/spawnClient.ts
src/autify/web/runTest.ts
src/commands/connect/access-point/set.ts
src/commands/connect/client/start.ts
src/commands/web/test/run.ts
src/config.ts
test/commands/connect/access-point/set.test.ts
test/commands/connect/client/start.test.ts

To integrate with Autify Connect Client, we add two commands for POC:
- `autify connect access-point set`
- `autify connect client start`
With these commands, the customer can store an Access Point information
and start Autify Connect Client without downloading its binary manually.
We also expand `autify web test run` by adding `--autify-connect-client`
flag. This single option starts Autify Connect Client and runs
a test scenario with the associated Access Point. This makes on-demand
test execution with given Access Point much easier.
----
Once we agree the CLI design, we'll add integration tests.

Add `connect` commands

---

.github/workflows/integration-tests.yml
README.md
package-lock.json
package.json
src/autify/connect/installClient.ts
src/autify/connect/spawnClient.ts
src/commands/connect/client/install.ts
src/commands/connect/client/start.ts
src/commands/web/test/run.ts
test/commands/connect/client/install.test.ts

To avoid majority of race conditions, we introduce a new command
just to install the Autify Connect Client binary.
The users need to install it first explicitly before using.
Also, bunch of internal code are improved including log handling

Add `connect client install` and internal improvements

---

integration-test/bin/autify-mobile-generate-fake-app.js
integration-test/package.json
integration-test/src/bin/autify-mobile-generate-fake-app.ts
package-lock.json

For mobile CI/CD integration tests, we need to generate fake apps
outside `autify-cli-integration-test`. Hence, exposing the command.
Note: We'll release this commit as a patch release of 0.7 as well.

Expose `autify-mobile-generate-fake-app`

---

integration-test/__recordings__/mobile%20build%20upload%20--workspace-id%3DnYmF1n%20ios.app/polly-proxy_3343057686/recording.har
integration-test/__snapshots__/golden/mobileBuildUploadIos.test.js.snap
integration-test/src/bin/autify-cli-integration-test.ts
integration-test/src/test/golden/mobileBuildUploadIos.test.ts
integration-test/src/test/helpers/testAutifyCliSnapshot.ts

Just adding one more recording and snapshot for `mobile build upload`
with iOS app file.
Also, moving the skip logic inside `testAutifyCliSnapshot`.
Close #90

Add mobileBuildUploadIos integration test

---

README.md
src/commands/mobile/test/run.ts
src/commands/mobile/test/wait.ts
src/commands/web/test/run.ts
src/commands/web/test/wait.ts

Sometime a test scenario is flaky and a few retires can pass it.
Close #102 
```
node ➜ /workspaces/autify-cli (feature/retry) $ ./bin/dev web test run https://app.autify.com/projects/743/scenarios/114338 --wait --max-retry-count 1
✅ Successfully started: https://app.autify.com/projects/743/results/1150087 (Capability is Linux Chrome 104.0)
🕐 Waiting for the test result: https://app.autify.com/projects/743/results/1150087
✔ Waiting... (timeout: 300 s)
❌ Test didn't pass. See https://app.autify.com/projects/743/results/1150087: {"id":1150087,"status":"failed","duration":6204,"started_at":"2022-09-05T18:14:37.670Z","finished_at":"2022-09-05T18:14:43.875Z","created_at":"2022-09-05T18:14:36.271Z","updated_at":"2022-09-05T18:14:45.444Z","review_needed":false,"test_plan_capability_results":[{"id …
```

Add `--max-retry-count` to `web/mobile test run`

---

README.md
src/commands/connect/client/start.ts
src/commands/web/test/run.ts

By this change, `connect client start` can create/delete an ephemeral access point on the specified workspace.

Add `--web-workspace-id` to `connect client start`

---

.github/workflows/upload.yml
install-cicd.bash
install-standalone.sh
scripts/release.ts

We provides only 32 bit binary for Arm and it doesn't work well on 64 bit Linux.
This commit provides the `linux-arm64` binary as well as updates on the installer script.
Close #108

Add `linux-arm64` binary

---

patches/oclif+3.1.2.patch

oclif provided cmd files are not good when terminating by ctrl+c because they always ask confirmation.
This patch update these files and no more confirmation will be asked.

Patch windows cmd files to avoid exit confirmation

---

README.md
src/autify/connect/installClient.ts
src/autify/connect/spawnClient.ts
src/commands/connect/client/install.ts
src/commands/connect/client/start.ts
src/commands/web/test/run.ts

We should lock the version of `autifyconnect` to avoid using backward incompatible release of `autifyconnect` and keep our integration tests idempotent.
This commit introduces "supported version" hard coded and installing that version by `connect client install` by default.
Optionally, the customers can install any specific version for some reasons, but we'll warn them when running `connect client start` or `web test run --autify-connect-client`.

Add supported `autifyconnect` version

---

README.md
integration-test/__recordings__/web%20test%20run%20--autify-connect-client%20--wait%20https%3A%2F%2Fapp.autify.com%2Fprojects%2F743%2Fscenarios%2F91437/polly-proxy_3343057686/recording.har
integration-test/__snapshots__/golden/webTestRunAutifyConnectClient.test.js.snap
src/autify/connect/spawnClient.ts
src/commands/connect/client/start.ts
src/commands/web/test/run.ts

Autify Connect Client added a experimental feature to provide a debug server for communicating with the client.
This commit adds support for that debug server and use it for `waitReady()` and `kill()` (not implemented yet by `autifyconnect`).
Also, moved some logics to properly finalize the commands.

Support debug server of Autify Connect client

---

README.md
src/autify/connect/accessPointConfig.ts
src/commands/connect/access-point/create.ts
src/commands/connect/access-point/set.ts
test/commands/connect/access-point/create.test.ts

This commit adds a new command to create an Access Point by the given name from CLI and store its key in the config file.
Also, `connect access-point set` gets more guardrail and logs along with the new command.

Add `connect access-point create`

---

patches/@oclif+plugin-update+3.0.0.patch
patches/oclif+3.2.1.patch

The previous update to the cmd files breaks `autify update` functionality
because it doesn't pass the environment variables.
This commit fixes the bug and also upgrade one more cmd in
`@oclif/plugin-update` package.

Fix Windows cmd files for the update issue

---

README.md
src/commands/connect/access-point/create.ts
src/commands/connect/access-point/set.ts
src/commands/connect/client/install.ts
src/commands/connect/client/start.ts
src/commands/web/test/run.ts

Since we've implemented enough integration tests, better Windows support, and maintainable code based on `xstate`, we'd like to remove the experimental tags from help messages of Autify Connect commands.

Remove experimental tags from Autify Connect commands

---

integration-test/__recordings__/web%20test%20run%20--autify-connect-client%20--wait%20https%3A%2F%2Fapp.autify.com%2Fprojects%2F743%2Fscenarios%2F91437/polly-proxy_3343057686/recording.har
integration-test/__snapshots__/golden/webTestRunAutifyConnectClient.test.js.snap
src/autify/connect/client-manager/Logger.ts

Previously we removed timestamp from console log for client and manager, but it's useful to see the behavior with timestamp.
This commit reverts it back.

Revert back timestamp in client console log

---

.github/workflows/upload.yml
scripts/release.ts

To support version lock in other integrations, we should upload shell installer for each specific version.

Upload shell installer to versions

---

.github/workflows/integration-tests.yml
install-cicd.bash

Most of CI/CD providers support Windows with bash so that we should support them by CI/CD shell installer as well.

Support Windows by CI/CD shell installer

---

.github/workflows/integration-tests.yml
install-cicd.bash
scripts/release.ts

To integration test for CI/CD integrations reliable, the CI/CD shell installer should have ability to install the same version of integration package as well.

Support integration test installing by CI/CD installer

---

install-cicd.bash

It's hard to run integrated test before promotion. We just found a bug after the first push.

Fix typo in CI/CD installer

---

integration-test/src/test/helpers/execAutifyCli.ts

`autifyconnect` 0.6.2 has a race condition when calling `POST /terminate` of the debug server. This has been fixed but the patch hasn't been released.
This commit is just a workaround until the newer `autifyconnect` is released.

Workaround terminate error of `autifyconnect`

---

.github/workflows/cicd-tests.yml
.github/workflows/pull-requests.yml
.github/workflows/push-branch.yml
scripts/release.ts

To ensure the new change can work with the current CI/CD integrations, we add a new workflow for CI/CD integration test.
#92
First, GitHub Actions.

Run CI/CD integration tests

---

.github/workflows/integration-tests.yml
install-cicd.bash

We decided to return bash path from cicd-installer and let each CI/CD integration handle them.

Fix cicd-installer path

---

package-lock.json
package.json

`autify-sdk-js` 0.4.0 doesn't work with larger files. 0.5.0 fixes the issue and now the user can upload any size of file.
Previous error:
```
RangeError: Invalid array length
at Buffer.toJSON (node:buffer:1100:15)
at JSON.stringify (<anonymous>)
at StringBuilder.makeData (/opt/homebrew/Cellar/autify-cli/0.10.1/lib/client/0.11.0-beta.0-ab2b25b/node_modules/axios-logger/lib/common/string-builder.js:82:56)
at requestLogger (/opt/homebrew/Cellar/autify-cli/0.10.1/lib/client/0.11.0-beta.0-ab2b25b/node_modules/axios-logger/lib/logger/request.js:25:169)
```
Fix of `autify-sdk-js`: https://github.com/autifyhq/autify-sdk-js/pull/81

Fix `mobile build upload` for larger files

---

.github/workflows/integration-tests.yml

It looks like GitHub has removed `brew` from `ubuntu-lates`.
https://github.com/autifyhq/autify-cli/actions/runs/3132660914/jobs/5085265698#step:17:146

Removing ubuntu-latest from brew integration tests

---

scripts/generate-api-commands.ts
src/autify/connect/client-manager/ClientManager.ts
src/autify/mobile/getMobileClient.ts
src/autify/web/getWebClient.ts
src/commands/connect/access-point/create.ts
src/commands/mobile/api/describe-test-result.ts
src/commands/mobile/api/list-test-results.ts
src/commands/mobile/api/run-test-plan.ts
src/commands/mobile/api/upload-build.ts
src/commands/mobile/build/upload.ts
src/commands/mobile/test/run.ts
src/commands/mobile/test/wait.ts
src/commands/web/api/create-access-point.ts
src/commands/web/api/create-url-replacement.ts
src/commands/web/api/delete-access-point.ts
src/commands/web/api/delete-url-replacement.ts
src/commands/web/api/describe-result.ts
src/commands/web/api/describe-scenario.ts
src/commands/web/api/execute-scenarios.ts
src/commands/web/api/execute-schedule.ts
src/commands/web/api/list-access-points.ts
src/commands/web/api/list-capabilities.ts
src/commands/web/api/list-results.ts
src/commands/web/api/list-scenarios.ts
src/commands/web/api/list-url-replacements.ts
src/commands/web/api/update-url-replacement.ts
src/commands/web/test/run.ts
src/commands/web/test/wait.ts
src/config.ts

To measure CLI usage deeply, this commit adds support to add prefix to the user agent via `AUTIFY_CLI_USER_AGENT_SUFFIX` environment variable.
This commit also refactor web/mobile client instantiations by centralizing them.
Close #170

Add `AUTIFY_CLI_USER_AGENT_SUFFIX`

---

README.md
integration-test/__recordings__/web%20test%20run%20--autify-connect-client%20--wait%20https%3A%2F%2Fapp.autify.com%2Fprojects%2F743%2Ftest_plans%2F169408/polly-proxy_3343057686/recording.har
integration-test/__recordings__/web%20test%20run%20--wait%20https%3A%2F%2Fapp.autify.com%2Fprojects%2F743%2Ftest_plans%2F169408/polly-proxy_3343057686/recording.har
integration-test/__recordings__/web%20test%20run%20https%3A%2F%2Fapp.autify.com%2Fprojects%2F743%2Ftest_plans%2F169408/polly-proxy_3343057686/recording.har
integration-test/__snapshots__/golden/webTestRunTestPlan.test.js.snap
integration-test/__snapshots__/golden/webTestRunTestPlanAutifyConnectClient.test.js.snap
integration-test/__snapshots__/golden/webTestRunTestPlanWait.test.js.snap
integration-test/src/commands.ts
integration-test/src/test/golden/webTestRunTestPlan.test.ts
integration-test/src/test/golden/webTestRunTestPlanAutifyConnectClient.test.ts
integration-test/src/test/golden/webTestRunTestPlanWait.test.ts
src/autify/web/runTest.ts
src/commands/web/test/run.ts

Since `executeSchedule` API is updated, we can now set Autify Connect Access Point when calling this API.
This commit add `autify-connect` and `autify-connect-client` support for test plan execution of `web test run`.

Support Autify Connect with test plan

---

bin/dev
bin/run
package-lock.json
package.json

The commit for checking it in beta channel. Before bumping `autify-cli` version, we need to release newer `autify-sdk-js` and switch to the version in `autify-cli`.

Update autify-sdk-js to use Axios v1

---

.github/actions/setup/action.yml

We shouldn't stick to a specific patch version.

Fix actions/setup-node version to major only

---

scripts/release.ts

See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Migrate to `GITHUB_OUTPUT` from `set-output`

---

renovate.json

I setup renovate bot via this PR https://github.com/autifyhq/autify-cli/pull/324
As a result we got single PR for updating but it contains both major and minor https://github.com/autifyhq/autify-cli/pull/325
I'd like to exclude major update

Combine non major update only

---

renovate.json

4.17.16 made the CI failed and we need to wait for merging a patch. https://github.com/DefinitelyTyped/DefinitelyTyped/pull/64042

chore: exclude types/express 4.17.16

---

install-cicd.bash

Currently nightly build for https://github.com/autifyhq/actions-web-test-run is failing.
https://github.com/autifyhq/actions-web-test-run/actions/workflows/nightly-test.yml
https://github.com/autifyhq/actions-web-test-run/actions/runs/5227107621/jobs/9438416832
It seems windows-latest image was updated and now it uses new version of Git for Windows.
On Git for Windows v2.41.0, `cmd.exe /C` won't run without `MSYS_NO_PATHCONV` because it converts the option to Windows path
> * If you specify command-line options starting with a slash, POSIX-to-Windows path conversion will kick in converting e.g. "`/usr/bin/bash.exe`" to "`C:\Program Files\Git\usr\bin\bash.exe`". When that is not desired -- e.g. "`--upload-pack=/opt/git/bin/git-upload-pack`" or "`-L/regex/`" -- you need to set the …

ADD MSYS_NO_PATHCONV=1 to fix windows build

---

.github/actions/setup/action.yml

The node16 version is deprecated. Use the newest version of aws-actions/configure-aws-credentials

Update node version of github action

---

package-lock.json
package.json
src/autify/connect/accessPointConfig.ts
src/autify/connect/client-manager/ClientManager.ts
src/autify/connect/client-manager/DebugServerClient.ts
src/autify/connect/installClient.ts
src/autify/mobile/createZip.ts
src/autify/mobile/inspectBuildFile.ts
src/autify/mobile/mobilelink/installBinary.ts
src/autify/mobile/mobilelink/mobile-link-manager/MobileLinkManager.ts
src/autify/mobile/parseTestPlanUrl.ts
src/autify/mobile/parseTestResultUrl.ts
src/autify/mobile/uploadBuild.ts
src/autify/mobile/waitTestResult.ts
src/autify/web/parseAutifyTestUrl.ts
src/autify/web/parseTestResultUrl.ts
src/autify/web/runTest.ts
src/autify/web/waitTestResult.ts
src/commands/mobile/test/run.ts
src/commands/web/test/run.ts

This PR removes the @oclif/errors dependency as it's deprecated and its functionality is now covered by @oclif/core. All imports of CLIError have been updated to use Errors.CLIError from @oclif/core instead.

[chore] Remove @oclif/errors dependency and use @oclif/core instead

---

src/autify/mobile/mobilelink/mobile-link-manager/MobileLinkManager.ts
src/commands/mobile/link/install.ts
src/commands/mobile/link/setup.ts

https://autifyhq.atlassian.net/browse/MOB-2368
This patch would add a new command `mobile link setup`, which invokes the same command in the `mobikelink`. Since I want to minimize the steps users have to run, I made it run installation commands for Autify Client and MobileLink if there don't exist.
Obviously the installation code is redundant. I searched for a way to composite commands in oclif so that I can reuse another command from one command but I found nothing, unfortunately.
When yet to be installed:
```
$ ./bin/dev mobile link setup
Installing Autify Connect Client from https://autifyconnect.s3.ap-northeast-1.amazonaws.com/autifyconnect/versions/stable/autifyconnect_darwin_arm64.tar.gz)... done
Successfully installed Autify Connect Client (path: …
```

Add `mobile link setup` command

---

src/autify/mobile/mobilelink/mobile-link-manager/MobileLinkManager.ts
src/commands/mobile/link/doctor.ts

https://autifyhq.atlassian.net/browse/MOB-2368
This patch would add `mobile link doctor` command which verifies the configuration on local device execution.
```
$ ./bin/dev mobile link doctor
[Mobile Link Manager]     2025-03-19T07:00:48.808Z      info    Executing MobileLink (path: /Users/tai2/Library/Caches/autify/mobilelink/bin/mobilelink, args: link doctor, version: mobilelink/0.2.1 darwin-arm64 node-v22.14.0)
✔ Xcode is installed.
✔ Xcode Command Line Tools are installed.
✔ Xcode version: 16.2
✔ Connected iOS device(s) found:
- Taiju’s iPhone (00008030-0008459A0A3B802E)
✔ Access token is valid.
✔ All checks passed. ✔
```

Add doctor command

---

src/autify/mobile/mobilelink/mobile-link-manager/MobileLinkManager.ts

https://autifyhq.atlassian.net/browse/MOB-2368
~This patch would make Autify CLI pass the `AUTIFY_CLI_INTEGRATION` and other variables to MobileLink so that it can receive necessary information from Autify CLI and change the behavior.~ As a result of a discussion in #4531, I stopped specifying the `AUTIFY_CLI_INTEGRATION` variable.
See https://github.com/autifyhq/mobile-web/pull/4531 as well
The reason I don't pass extra variables on `link exec` is I want to keep the original behavior since it's low layer.
----
The necessary steps for setup for users will look like this:
```
autify mobile auth
autify mobile link setup # users don't need to run `install` commands explicitly
autify mobile start
```
In a separate terminal
```
autify mobile run $TEST_PLAN_URL --device_ids …
```

Pass AUTIFY_CLI_INTEGRATION variable and others

---

src/commands/mobile/test/run.ts

https://autifyhq.atlassian.net/browse/MOB-2368
This patch would add `--device-ids` flag so that users can run local device tests.

Add deivce-ids to mobile test run command

---

src/autify/mobile/mobilelink/mobile-link-manager/Logger.ts

I've noticed some information in the logs from mobilelink is dropped. This is because the structured logs of mobilelink contain properties other than messages but Autify CLI presumes it contains only messages. This patch would include all information in the logs.
Before
```
[Mobile Link]             2025-03-31T03:04:13.168Z      info    Found device
[Mobile Link]             2025-03-31T03:04:13.168Z      info    Found device
[Mobile Link]             2025-03-31T03:04:13.168Z      info    Found device
[Mobile Link]             2025-03-31T03:04:13.168Z      info    Found device
```
After
```
[Mobile Link]             2025-03-31T03:03:05.237Z      info    {"deviceId":"4285F3C0-2624-4215-B982-EE0F5C8266BA","isRealDevice":false,"message":"Found device","name":"iPad Air (4th …
```

Fix: some information from MobileLink is dropped

---

src/autify/mobile/mobilelink/installBinary.ts

Ticket: https://autifyhq.atlassian.net/browse/MOB-2439
`autify mobile link install` fails with this error:
```
Installing Mobile Link from https://d21jojv86oc6d1.cloudfront.net/mobilelink/channels/stable/mobilelink-darwin-amd64.tar.gz)... !
›   Error: Failed to fetch https://d21jojv86oc6d1.cloudfront.net/mobilelink/ch
›   annels/stable/mobilelink-darwin-amd64.tar.gz: 403
```

Fix: wrong file name of mobilelink on intel

---

e2e-test/mobile/local-execution-flow.test.ts

I've noticed there's a mistake and E2E test always lasts more than 15 minutes even if it's finished early.

Fix: E2E test always last 15 minutes

---

src/autify/mobile/mobilelink/installBinary.ts

Update Mobile Link version to newest release:
https://github.com/autifyhq/mobile-web/pull/4556 add persistent list of local devices on start command
https://github.com/autifyhq/mobile-web/pull/4558 bump mobile link version to 0.3.1

bump mobile link version

---

src/autify/mobile/mobilelink/installBinary.ts

It contains a fix for the local Android device.
cf https://github.com/autifyhq/mobile-web/pull/4707

Bump mobilelink to 0.4.6
